"""empty message

Revision ID: b4dfb32e7603
Revises: 412e8baa58b8
Create Date: 2016-03-05 19:09:31.632097

"""

# revision identifiers, used by Alembic.
revision = 'b4dfb32e7603'
down_revision = '412e8baa58b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iterms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('voted_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['voted_id'], ['iterms.id'], ),
    sa.PrimaryKeyConstraint('voted_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('iterms')
    ### end Alembic commands ###
