"""empty message

Revision ID: cb9ff1f36cc1
Revises: a73d6fb97595
Create Date: 2016-03-06 15:49:59.372663

"""

# revision identifiers, used by Alembic.
revision = 'cb9ff1f36cc1'
down_revision = 'a73d6fb97595'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('selected', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vote_id'], ['vote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('iterm')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iterm',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vote_id', sa.INTEGER(), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('selected', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['vote_id'], [u'vote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item')
    ### end Alembic commands ###
